version: '3.8'

services:  
  app:    
    build:     
      context: .    
      dockerfile: Dockerfile    
    image: sistema-gestor:latest    
    ports:      
      - "8080:8080"    
    restart: always   
    entrypoint: ["java", "-jar", "sistema-gestor.war"]